spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
  datasource:
    url: ${SPRING_DATA_SOURCE_URL}
    username: ${SPRING_DATA_SOURCE_USERNAME}
    password: ${SPRING_DATA_SOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATA_SOURCE_DRIVER_CLASSNAME}
  jwt:
    rsa:
      private-key: ${PRIVATE_KEY}
      public-key: ${PUBLIC_KEY}
    expires-time: ${EXPIRES_TIME}
  cookie:
    expires-time: ${EXPIRES_TIME}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

server:
  port: ${SPRING_APPLICATION_PORT:8080}

client:
  url: ${CLIENT_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

open:
  api:
    title: StudentCodeHub API Document
    version: 0.0.1
    description: StudentCodeHub API Document
    local-server-url: ${OPEN_API_LOCAL_SERVER_URL}
    host-server-url: ${OPEN_API_HOST_SERVER_URL}

logging:
  level:
    root: DEBUG

bcrypt:
  log-rounds: 10