spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  output:
    ansi:
      enabled: detect
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    show-sql: false
  datasource:
    url: ${SPRING_DATA_SOURCE_URL}
    username: ${SPRING_DATA_SOURCE_USERNAME}
    password: ${SPRING_DATA_SOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATA_SOURCE_DRIVER_CLASSNAME}
  jwt:
    rsa:
      private-key: ${PRIVATE_KEY}
      public-key: ${PUBLIC_KEY}
    expires-time: ${EXPIRES_TIME}
  cookie:
    expires-time: ${EXPIRES_TIME}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

server:
  port: ${SPRING_APPLICATION_PORT:8080}

client:
  url: ${CLIENT_URL}

server:
  url: ${SERVER_URL}

judge0:
  max_cpu_time_limit: ${MAX_CPU_TIME_LIMIT}
  max_cpu_extra_time: ${MAX_CPU_EXTRA_TIME}
  max_wall_time_limit: ${MAX_WALL_TIME_LIMIT}
  max_memory_limit: ${MAX_MEMORY_LIMIT}
  max_stack_limit: ${MAX_STACK_LIMIT}
  max_max_processes_and_or_threads: ${MAX_MAX_PROCESSES_AND_OR_THREADS}
  allow_enable_per_process_and_thread_time_limit: ${ALLOW_ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT}
  allow_enable_per_process_and_thread_memory_limit: ${ALLOW_ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT}
  max_max_file_size: ${MAX_MAX_FILE_SIZE}
  max_number_of_runs: ${MAX_NUMBER_OF_RUNS}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

open:
  api:
    title: StudentCodeHub API Document
    version: 0.0.1
    description: StudentCodeHub API Document
    local-server-url: ${OPEN_API_LOCAL_SERVER_URL}
    host-server-url: ${OPEN_API_HOST_SERVER_URL}

logging:
  level:
    root: DEBUG

bcrypt:
  log-rounds: 10