name: Docker Compose CI/CD

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Compose
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Environment Variables and Write to .env File
        run: |
          echo "SPRING_APPLICATION_NAME=${{ vars.SPRING_APPLICATION_NAME }}" >> .env
          echo "SPRING_APPLICATION_PORT=${{ vars.SPRING_APPLICATION_PORT }}" >> .env
          
          echo "CLIENT_URL=${{ vars.CLIENT_URL }}" >> .env
          echo "SERVER_URL=${{ vars.SERVER_URL }}" >> .env
          echo "JUDGE0_URL=${{ vars.JUDGE0_URL }}" >> .env

          echo "SPRING_JPA_HIBERNATE_DDL_AUTO=${{ vars.SPRING_JPA_HIBERNATE_DDL_AUTO }}" >> .env
          echo "SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${{ vars.SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT }}" >> .env
          echo "SPRING_DATA_SOURCE_URL=${{ secrets.SPRING_DATA_SOURCE_URL }}" >> .env
          echo "SPRING_DATA_SOURCE_USERNAME=${{ secrets.SPRING_DATA_SOURCE_USERNAME }}" >> .env
          echo "SPRING_DATA_SOURCE_PASSWORD=${{ secrets.SPRING_DATA_SOURCE_PASSWORD }}" >> .env
          echo "SPRING_DATA_SOURCE_DRIVER_CLASSNAME=${{ vars.SPRING_DATA_SOURCE_DRIVER_CLASSNAME }}" >> .env

          echo "PRIVATE_KEY=${{ vars.PRIVATE_KEY }}" >> .env
          echo "PUBLIC_KEY=${{ vars.PUBLIC_KEY }}" >> .env
          echo "ACCESS_TOKEN_EXPIRES_TIME=${{ vars.ACCESS_TOKEN_EXPIRES_TIME }}" >> .env
          echo "REFRESH_TOKEN_EXPIRES_TIME=${{ vars.REFRESH_TOKEN_EXPIRES_TIME }}" >> .env

          echo "JUDGE0_AUTH_TOKEN=${{ secrets.JUDGE0_AUTH_TOKEN }}" >> .env

          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env

          echo "OPEN_API_LOCAL_SERVER_URL=${{ vars.OPEN_API_LOCAL_SERVER_URL }}" >> .env
          echo "OPEN_API_HOST_SERVER_URL=${{ vars.OPEN_API_HOST_SERVER_URL }}" >> .env

          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env

      - name: Build and Deploy Docker Compose
        run: |
          docker-compose --env-file .env build
          docker-compose --env-file .env up -d
